<?php
/**
 * MarketplaceApiTest
 * PHP version 8.1
 *
 * @package  eBay\Sell\Metadata
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Metadata API
 *
 * The Metadata API has operations that retrieve configuration details pertaining to the different eBay marketplaces. In addition to marketplace information, the API also has operations that get information that helps sellers list items on eBay.
 *
 * The version of the OpenAPI document: v1.9.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace eBay\Sell\Metadata\Test\Api;

use eBay\Sell\Metadata\Configuration;
use eBay\Sell\Metadata\ApiException;
use eBay\Sell\Metadata\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MarketplaceApiTest Class Doc Comment
 *
 * @package  eBay\Sell\Metadata
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MarketplaceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getAutomotivePartsCompatibilityPolicies
     *
     * .
     *
     */
    public function testGetAutomotivePartsCompatibilityPolicies()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getExtendedProducerResponsibilityPolicies
     *
     * .
     *
     */
    public function testGetExtendedProducerResponsibilityPolicies()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getHazardousMaterialsLabels
     *
     * .
     *
     */
    public function testGetHazardousMaterialsLabels()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getItemConditionPolicies
     *
     * .
     *
     */
    public function testGetItemConditionPolicies()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getListingStructurePolicies
     *
     * .
     *
     */
    public function testGetListingStructurePolicies()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getNegotiatedPricePolicies
     *
     * .
     *
     */
    public function testGetNegotiatedPricePolicies()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProductSafetyLabels
     *
     * .
     *
     */
    public function testGetProductSafetyLabels()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRegulatoryPolicies
     *
     * .
     *
     */
    public function testGetRegulatoryPolicies()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getReturnPolicies
     *
     * .
     *
     */
    public function testGetReturnPolicies()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
