<?php

/**
 * AdFormatEnabledEnum
 *
 * PHP version 8.1
 *
 * @package  eBay\Sell\Metadata
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Metadata API
 *
 * The Metadata API provides crucial configuration details necessary for managing listings across various eBay marketplaces. This includes retrieving detailed eBay category listing policies, such as supported item conditions and multiple-variation structures; accessing sales tax jurisdiction information for setting up tax tables in supported countries; and obtaining hazardous material and product safety label data for regulatory compliance in listing flows. The API is essential for sellers and developers needing up-to-date, marketplace-specific policy and jurisdictional information to accurately create and manage their listings.
 *
 * The version of the OpenAPI document: v1.13.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace eBay\Sell\Metadata\Model;

/**
 * AdFormatEnabledEnum Class Doc Comment
 *
 * @description This enumerated type contains a list of values indicating type or status of available ad formats for an eBay site or for an eBay category. | - **DISABLED**: This value indicates that the Classified Ad format feature is disabled for the site or category. - **ENABLED**: This value indicates that the Classified Ad format feature is enabled for the site or category. - **ONLY**: This value indicates that the Classified Ad format is the only listing type supported by the eBay category. This value is not applicable at the eBay site level. - **CLASSIFIED_AD_ENABLED**: This value indicates that the lead-generation Classified Ad format is the only listing type supported by the eBay category. This value is not applicable at the eBay site level. - **CLASSIFIED_AD_ONLY**: This value indicates that the lead-generation Classified Ad format is the only listing type supported by the eBay category. This value is not applicable at the eBay site level. - **LOCAL_MARKET_BEST_OFFER_ONLY**: This value indicates that eBay Motors Local Market listings are enabled for the site or category.
 * @package  eBay\Sell\Metadata
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum AdFormatEnabledEnum: string
{
    case DISABLED = 'DISABLED';

    case ENABLED = 'ENABLED';

    case ONLY = 'ONLY';

    case CLASSIFIED_AD_ENABLED = 'CLASSIFIED_AD_ENABLED';

    case CLASSIFIED_AD_ONLY = 'CLASSIFIED_AD_ONLY';

    case LOCAL_MARKET_BEST_OFFER_ONLY = 'LOCAL_MARKET_BEST_OFFER_ONLY';
}


