<?php

/**
 * ClassifiedAdBestOfferEnabledEnum
 *
 * PHP version 8.1
 *
 * @package  eBay\Sell\Metadata
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Metadata API
 *
 * The Metadata API provides crucial configuration details necessary for managing listings across various eBay marketplaces. This includes retrieving detailed eBay category listing policies, such as supported item conditions and multiple-variation structures; accessing sales tax jurisdiction information for setting up tax tables in supported countries; and obtaining hazardous material and product safety label data for regulatory compliance in listing flows. The API is essential for sellers and developers needing up-to-date, marketplace-specific policy and jurisdictional information to accurately create and manage their listings.
 *
 * The version of the OpenAPI document: v1.13.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace eBay\Sell\Metadata\Model;

/**
 * ClassifiedAdBestOfferEnabledEnum Class Doc Comment
 *
 * @description This enumerated type defines values that indicate whether the category supports Classified Ad Best Offers. | - **DISABLED**: This value indicates that Classified Ad Best Offer feature is disabled for most categories. - **ENABLED**: This value indicates that Classified Ad Best Offer feature is enabled for most categories. - **REQUIRED**: This value indicates that Classified Ad Best Offer feature is required for a specific category.
 * @package  eBay\Sell\Metadata
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum ClassifiedAdBestOfferEnabledEnum: string
{
    case DISABLED = 'DISABLED';

    case ENABLED = 'ENABLED';

    case REQUIRED = 'REQUIRED';
}


