<?php

/**
 * DistanceType
 *
 * PHP version 8.1
 *
 * @package  eBay\Sell\Metadata
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Metadata API
 *
 * The Metadata API provides crucial configuration details necessary for managing listings across various eBay marketplaces. This includes retrieving detailed eBay category listing policies, such as supported item conditions and multiple-variation structures; accessing sales tax jurisdiction information for setting up tax tables in supported countries; and obtaining hazardous material and product safety label data for regulatory compliance in listing flows. The API is essential for sellers and developers needing up-to-date, marketplace-specific policy and jurisdictional information to accurately create and manage their listings.
 *
 * The version of the OpenAPI document: v1.13.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace eBay\Sell\Metadata\Model;

/**
 * DistanceType Class Doc Comment
 *
 * @description This enumeration type indicates support of local listing distances for items listed by sellers. | - **LOCAL_LISTING_DISTANCES_REGULAR**: Indicates that one or more eBay marketplaces allow dealership subscribers with a regular subscription to specify local market radius for Motors Local Market listings. - **LOCAL_LISTING_DISTANCES_SPECIALTY**: Indicates that one or more eBay marketplaces allow dealership subscribers with a specialty subscription to specify local market radius for Motors Local Market listings. - **LOCAL_LISTING_DISTANCES_NON_SUBSCRIPTION**: Indicates that one or more eBay marketplaces allow dealership subscribers without a subscription to specify local market radius for Motors Local Market listings.
 * @package  eBay\Sell\Metadata
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum DistanceType: string
{
    case LOCAL_LISTING_DISTANCES_REGULAR = 'LOCAL_LISTING_DISTANCES_REGULAR';

    case LOCAL_LISTING_DISTANCES_SPECIALTY = 'LOCAL_LISTING_DISTANCES_SPECIALTY';

    case LOCAL_LISTING_DISTANCES_NON_SUBSCRIPTION = 'LOCAL_LISTING_DISTANCES_NON_SUBSCRIPTION';
}


