<?php

/**
 * ExtendedProducerResponsibilityEnum
 *
 * PHP version 8.1
 *
 * @package  eBay\Sell\Metadata
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Metadata API
 *
 * The Metadata API provides crucial configuration details necessary for managing listings across various eBay marketplaces. This includes retrieving detailed eBay category listing policies, such as supported item conditions and multiple-variation structures; accessing sales tax jurisdiction information for setting up tax tables in supported countries; and obtaining hazardous material and product safety label data for regulatory compliance in listing flows. The API is essential for sellers and developers needing up-to-date, marketplace-specific policy and jurisdictional information to accurately create and manage their listings.
 *
 * The version of the OpenAPI document: v1.13.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace eBay\Sell\Metadata\Model;

/**
 * ExtendedProducerResponsibilityEnum Class Doc Comment
 *
 * @description An enumerated type that identifies the attributes used in Extended Producer Responsibility policies.&lt;span class&#x3D;\&quot;tablenote\&quot;&gt;&lt;span style&#x3D;\&quot;color:#478415\&quot;&gt;&lt;strong&gt;Note: &lt;/strong&gt;&lt;/span&gt;Extended Producer Responsibility IDs are no longer set at the listing level so category-level metadata is no longer returned for &lt;code&gt;PRODUCER_PRODUCT_ID&lt;/code&gt;, &lt;code&gt;PRODUCT_DOCUMENTATION_ID&lt;/code&gt;, &lt;code&gt;PRODUCT_PACKAGE_ID&lt;/code&gt;, and &lt;code&gt;SHIPMENT_PACKAGE_ID&lt;/code&gt;. Sellers will provide/manage these IDs at the account level by going to &lt;a href&#x3D;\&quot;https://accountsettings.ebay.fr/epr-fr \&quot; target&#x3D;\&quot;_blank\&quot;&gt;Account Settings&lt;/a&gt;.&lt;/span&gt; | - **ECO_PARTICIPATION_FEE**: This enum value is used to identify the eco participation fee attribute. - **TAKE_BACK_POLICY**: This enum value is used to identify the take-back policy attribute. - **REPAIR_SCORE**: This enum value is used to identify the repair score attribute.
 * @package  eBay\Sell\Metadata
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum ExtendedProducerResponsibilityEnum: string
{
    case ECO_PARTICIPATION_FEE = 'ECO_PARTICIPATION_FEE';

    case TAKE_BACK_POLICY = 'TAKE_BACK_POLICY';

    case REPAIR_SCORE = 'REPAIR_SCORE';
}


