<?php

/**
 * PackageLimits
 *
 * PHP version 8.1
 *
 * @package  eBay\Sell\Metadata
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Metadata API
 *
 * The Metadata API has operations that retrieve configuration details pertaining to the different eBay marketplaces. In addition to marketplace information, the API also has operations that get information that helps sellers list items on eBay.
 *
 * The version of the OpenAPI document: v1.12.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace eBay\Sell\Metadata\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use eBay\Sell\Metadata\ObjectSerializer;

/**
 * PackageLimits Class Doc Comment
 *
 * @description The packageLimits field is used to specify the physical constraints and measurement units of packages, ensuring compliance with various shipping requirements.
 * @package  eBay\Sell\Metadata
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class PackageLimits implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'PackageLimits';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'dimension_unit' => 'string',
        'max_girth' => 'float',
        'max_height' => 'float',
        'max_length' => 'float',
        'max_weight' => 'float',
        'max_width' => 'float',
        'min_girth' => 'float',
        'min_height' => 'float',
        'min_length' => 'float',
        'min_weight' => 'float',
        'min_width' => 'float',
        'weight_unit' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'dimension_unit' => null,
        'max_girth' => null,
        'max_height' => null,
        'max_length' => null,
        'max_weight' => null,
        'max_width' => null,
        'min_girth' => null,
        'min_height' => null,
        'min_length' => null,
        'min_weight' => null,
        'min_width' => null,
        'weight_unit' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'dimension_unit' => false,
        'max_girth' => false,
        'max_height' => false,
        'max_length' => false,
        'max_weight' => false,
        'max_width' => false,
        'min_girth' => false,
        'min_height' => false,
        'min_length' => false,
        'min_weight' => false,
        'min_width' => false,
        'weight_unit' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'dimension_unit' => 'dimensionUnit',
        'max_girth' => 'maxGirth',
        'max_height' => 'maxHeight',
        'max_length' => 'maxLength',
        'max_weight' => 'maxWeight',
        'max_width' => 'maxWidth',
        'min_girth' => 'minGirth',
        'min_height' => 'minHeight',
        'min_length' => 'minLength',
        'min_weight' => 'minWeight',
        'min_width' => 'minWidth',
        'weight_unit' => 'weightUnit'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'dimension_unit' => 'setDimensionUnit',
        'max_girth' => 'setMaxGirth',
        'max_height' => 'setMaxHeight',
        'max_length' => 'setMaxLength',
        'max_weight' => 'setMaxWeight',
        'max_width' => 'setMaxWidth',
        'min_girth' => 'setMinGirth',
        'min_height' => 'setMinHeight',
        'min_length' => 'setMinLength',
        'min_weight' => 'setMinWeight',
        'min_width' => 'setMinWidth',
        'weight_unit' => 'setWeightUnit'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'dimension_unit' => 'getDimensionUnit',
        'max_girth' => 'getMaxGirth',
        'max_height' => 'getMaxHeight',
        'max_length' => 'getMaxLength',
        'max_weight' => 'getMaxWeight',
        'max_width' => 'getMaxWidth',
        'min_girth' => 'getMinGirth',
        'min_height' => 'getMinHeight',
        'min_length' => 'getMinLength',
        'min_weight' => 'getMinWeight',
        'min_width' => 'getMinWidth',
        'weight_unit' => 'getWeightUnit'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('dimension_unit', $data ?? [], null);
        $this->setIfExists('max_girth', $data ?? [], null);
        $this->setIfExists('max_height', $data ?? [], null);
        $this->setIfExists('max_length', $data ?? [], null);
        $this->setIfExists('max_weight', $data ?? [], null);
        $this->setIfExists('max_width', $data ?? [], null);
        $this->setIfExists('min_girth', $data ?? [], null);
        $this->setIfExists('min_height', $data ?? [], null);
        $this->setIfExists('min_length', $data ?? [], null);
        $this->setIfExists('min_weight', $data ?? [], null);
        $this->setIfExists('min_width', $data ?? [], null);
        $this->setIfExists('weight_unit', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets dimension_unit
     *
     * @return string|null
     */
    public function getDimensionUnit(): ?string
    {
        return $this->container['dimension_unit'];
    }

    /**
     * Sets dimension_unit
     *
     * @param string|null $dimension_unit Unit of dimensional measurement, for example <code>INCH</code> or <code>CENTIMETER</code>.
     *
     * @return $this
     */
    public function setDimensionUnit(?string $dimension_unit): static
    {
        if (is_null($dimension_unit)) {
            throw new InvalidArgumentException('non-nullable dimension_unit cannot be null');
        }
        $this->container['dimension_unit'] = $dimension_unit;

        return $this;
    }

    /**
     * Gets max_girth
     *
     * @return float|null
     */
    public function getMaxGirth(): ?float
    {
        return $this->container['max_girth'];
    }

    /**
     * Sets max_girth
     *
     * @param float|null $max_girth The maximum girth allowed for a package shipped through the corresponding shipping service, as measured in units of <a href=\"/api-docs/sell/metadata/resources/shipping:marketplace/methods/getShippingServices#response.shippingServices.packageLimits.dimensionUnit\">dimensionUnit</a>.
     *
     * @return $this
     */
    public function setMaxGirth(?float $max_girth): static
    {
        if (is_null($max_girth)) {
            throw new InvalidArgumentException('non-nullable max_girth cannot be null');
        }
        $this->container['max_girth'] = $max_girth;

        return $this;
    }

    /**
     * Gets max_height
     *
     * @return float|null
     */
    public function getMaxHeight(): ?float
    {
        return $this->container['max_height'];
    }

    /**
     * Sets max_height
     *
     * @param float|null $max_height The maximum height allowed for a package shipped through the corresponding shipping service, as measured in units of <a href=\"/api-docs/sell/metadata/resources/shipping:marketplace/methods/getShippingServices#response.shippingServices.packageLimits.dimensionUnit\">dimensionUnit</a>.
     *
     * @return $this
     */
    public function setMaxHeight(?float $max_height): static
    {
        if (is_null($max_height)) {
            throw new InvalidArgumentException('non-nullable max_height cannot be null');
        }
        $this->container['max_height'] = $max_height;

        return $this;
    }

    /**
     * Gets max_length
     *
     * @return float|null
     */
    public function getMaxLength(): ?float
    {
        return $this->container['max_length'];
    }

    /**
     * Sets max_length
     *
     * @param float|null $max_length The maximum length allowed for a package shipped through the corresponding shipping service, as measured in units of <a href=\"/api-docs/sell/metadata/resources/shipping:marketplace/methods/getShippingServices#response.shippingServices.packageLimits.dimensionUnit\">dimensionUnit</a>.
     *
     * @return $this
     */
    public function setMaxLength(?float $max_length): static
    {
        if (is_null($max_length)) {
            throw new InvalidArgumentException('non-nullable max_length cannot be null');
        }
        $this->container['max_length'] = $max_length;

        return $this;
    }

    /**
     * Gets max_weight
     *
     * @return float|null
     */
    public function getMaxWeight(): ?float
    {
        return $this->container['max_weight'];
    }

    /**
     * Sets max_weight
     *
     * @param float|null $max_weight The maximum weight allowed for a package shipped through the corresponding shipping service, as measured in units of <a href=\"/api-docs/sell/metadata/resources/shipping:marketplace/methods/getShippingServices#response.shippingServices.packageLimits.weightUnit\">weightUnit</a>.
     *
     * @return $this
     */
    public function setMaxWeight(?float $max_weight): static
    {
        if (is_null($max_weight)) {
            throw new InvalidArgumentException('non-nullable max_weight cannot be null');
        }
        $this->container['max_weight'] = $max_weight;

        return $this;
    }

    /**
     * Gets max_width
     *
     * @return float|null
     */
    public function getMaxWidth(): ?float
    {
        return $this->container['max_width'];
    }

    /**
     * Sets max_width
     *
     * @param float|null $max_width The maximum width allowed for a package shipped through the corresponding shipping service, as measured in units of <a href=\"/api-docs/sell/metadata/resources/shipping:marketplace/methods/getShippingServices#response.shippingServices.packageLimits.dimensionUnit\">dimensionUnit</a>.
     *
     * @return $this
     */
    public function setMaxWidth(?float $max_width): static
    {
        if (is_null($max_width)) {
            throw new InvalidArgumentException('non-nullable max_width cannot be null');
        }
        $this->container['max_width'] = $max_width;

        return $this;
    }

    /**
     * Gets min_girth
     *
     * @return float|null
     */
    public function getMinGirth(): ?float
    {
        return $this->container['min_girth'];
    }

    /**
     * Sets min_girth
     *
     * @param float|null $min_girth The minimum girth allowed for a package shipped through the corresponding shipping service, as measured in units of <a href=\"/api-docs/sell/metadata/resources/shipping:marketplace/methods/getShippingServices#response.shippingServices.packageLimits.dimensionUnit\">dimensionUnit</a>.
     *
     * @return $this
     */
    public function setMinGirth(?float $min_girth): static
    {
        if (is_null($min_girth)) {
            throw new InvalidArgumentException('non-nullable min_girth cannot be null');
        }
        $this->container['min_girth'] = $min_girth;

        return $this;
    }

    /**
     * Gets min_height
     *
     * @return float|null
     */
    public function getMinHeight(): ?float
    {
        return $this->container['min_height'];
    }

    /**
     * Sets min_height
     *
     * @param float|null $min_height The minimum height allowed for a package shipped through the corresponding shipping service, as measured in units of <a href=\"/api-docs/sell/metadata/resources/shipping:marketplace/methods/getShippingServices#response.shippingServices.packageLimits.dimensionUnit\">dimensionUnit</a>.
     *
     * @return $this
     */
    public function setMinHeight(?float $min_height): static
    {
        if (is_null($min_height)) {
            throw new InvalidArgumentException('non-nullable min_height cannot be null');
        }
        $this->container['min_height'] = $min_height;

        return $this;
    }

    /**
     * Gets min_length
     *
     * @return float|null
     */
    public function getMinLength(): ?float
    {
        return $this->container['min_length'];
    }

    /**
     * Sets min_length
     *
     * @param float|null $min_length The minimum length allowed for a package shipped through the corresponding shipping service, as measured in units of <a href=\"/api-docs/sell/metadata/resources/shipping:marketplace/methods/getShippingServices#response.shippingServices.packageLimits.dimensionUnit\">dimensionUnit</a>.
     *
     * @return $this
     */
    public function setMinLength(?float $min_length): static
    {
        if (is_null($min_length)) {
            throw new InvalidArgumentException('non-nullable min_length cannot be null');
        }
        $this->container['min_length'] = $min_length;

        return $this;
    }

    /**
     * Gets min_weight
     *
     * @return float|null
     */
    public function getMinWeight(): ?float
    {
        return $this->container['min_weight'];
    }

    /**
     * Sets min_weight
     *
     * @param float|null $min_weight The minimum weight allowed for a package shipped through the corresponding shipping service, as measured in units of <a href=\"/api-docs/sell/metadata/resources/shipping:marketplace/methods/getShippingServices#response.shippingServices.packageLimits.weightUnit\">weightUnit</a>.
     *
     * @return $this
     */
    public function setMinWeight(?float $min_weight): static
    {
        if (is_null($min_weight)) {
            throw new InvalidArgumentException('non-nullable min_weight cannot be null');
        }
        $this->container['min_weight'] = $min_weight;

        return $this;
    }

    /**
     * Gets min_width
     *
     * @return float|null
     */
    public function getMinWidth(): ?float
    {
        return $this->container['min_width'];
    }

    /**
     * Sets min_width
     *
     * @param float|null $min_width The minimum width allowed for a package shipped through the corresponding shipping service, as measured in units of <a href=\"/api-docs/sell/metadata/resources/shipping:marketplace/methods/getShippingServices#response.shippingServices.packageLimits.dimensionUnit\">dimensionUnit</a>.
     *
     * @return $this
     */
    public function setMinWidth(?float $min_width): static
    {
        if (is_null($min_width)) {
            throw new InvalidArgumentException('non-nullable min_width cannot be null');
        }
        $this->container['min_width'] = $min_width;

        return $this;
    }

    /**
     * Gets weight_unit
     *
     * @return string|null
     */
    public function getWeightUnit(): ?string
    {
        return $this->container['weight_unit'];
    }

    /**
     * Sets weight_unit
     *
     * @param string|null $weight_unit Unit of weight measurement, for example <code>KILOGRAM</code> or <code>OUNCE</code>.
     *
     * @return $this
     */
    public function setWeightUnit(?string $weight_unit): static
    {
        if (is_null($weight_unit)) {
            throw new InvalidArgumentException('non-nullable weight_unit cannot be null');
        }
        $this->container['weight_unit'] = $weight_unit;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


