<?php

/**
 * PaymentEnum
 *
 * PHP version 8.1
 *
 * @package  eBay\Sell\Metadata
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Metadata API
 *
 * The Metadata API provides crucial configuration details necessary for managing listings across various eBay marketplaces. This includes retrieving detailed eBay category listing policies, such as supported item conditions and multiple-variation structures; accessing sales tax jurisdiction information for setting up tax tables in supported countries; and obtaining hazardous material and product safety label data for regulatory compliance in listing flows. The API is essential for sellers and developers needing up-to-date, marketplace-specific policy and jurisdictional information to accurately create and manage their listings.
 *
 * The version of the OpenAPI document: v1.13.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace eBay\Sell\Metadata\Model;

/**
 * PaymentEnum Class Doc Comment
 *
 * @description An enumerated type that defines the different payment methods that can be used by buyers to pay sellers for purchases.&lt;p&gt;&lt;span class&#x3D;\&quot;tablenote\&quot;&gt;&lt;span style&#x3D;\&quot;color:#004680\&quot;&gt;&lt;strong&gt;Note: &lt;/strong&gt;This value is only applicable for offline payments.&lt;/span&gt;&lt;/p&gt; | - **CASH_ON_PICKUP**: This enumeration value indicates that cash on pickup is accepted for payment. This value is only applicable for offline payments. - **PAYMENT_SEE_DESCRIPTION**: This enumeration value indicates that payment format is described in the listing description. This value is only applicable for offline payments and is not supported on all marketplaces. - **MOCC**: This enumeration value indicates that a money order or cashiers check is accepted for payment. This value is only applicable for offline payments and is not supported on all marketplaces. - **PERSONAL_CHECK**: This enumeration value indicates that a personal check is accepted for payment. This value is only applicable for offline payments and is not supported on all marketplaces. - **OTHER**: This enumeration value indicates that the payment format accepted for payment is not described by any of the other payment methods. This value is only applicable for offline payments.
 * @package  eBay\Sell\Metadata
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum PaymentEnum: string
{
    case CASH_ON_PICKUP = 'CASH_ON_PICKUP';

    case PAYMENT_SEE_DESCRIPTION = 'PAYMENT_SEE_DESCRIPTION';

    case MOCC = 'MOCC';

    case PERSONAL_CHECK = 'PERSONAL_CHECK';

    case OTHER = 'OTHER';
}


