<?php

/**
 * ProductIdentiferEnabledEnum
 *
 * PHP version 8.1
 *
 * @package  eBay\Sell\Metadata
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Metadata API
 *
 * The Metadata API provides crucial configuration details necessary for managing listings across various eBay marketplaces. This includes retrieving detailed eBay category listing policies, such as supported item conditions and multiple-variation structures; accessing sales tax jurisdiction information for setting up tax tables in supported countries; and obtaining hazardous material and product safety label data for regulatory compliance in listing flows. The API is essential for sellers and developers needing up-to-date, marketplace-specific policy and jurisdictional information to accurately create and manage their listings.
 *
 * The version of the OpenAPI document: v1.13.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace eBay\Sell\Metadata\Model;

/**
 * ProductIdentiferEnabledEnum Class Doc Comment
 *
 * @description This enumerated type specifies whether a leaf category supports or requires a Universal Product Code (UPC), International Standard Book Number (ISBN), or European Article Number (EAN) for products. Collectively, these identifiers are referred to as Global Trade Item Numbers (GTINs).&lt;/p&gt; | - **DISABLED**: This value indicates that the corresponding Global Trade Item Number (GTIN) type is not supported for the leaf category. - **ENABLED**: This value indicates that the corresponding Global Trade Item Number (GTIN) type is supported as applicable, but not required for the leaf category - **REQUIRED**: This value indicates that the corresponding Global Trade Item Number (GTIN) type is required for the leaf category, and an Add/Revise operation will fail without this information.
 * @package  eBay\Sell\Metadata
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum ProductIdentiferEnabledEnum: string
{
    case DISABLED = 'DISABLED';

    case ENABLED = 'ENABLED';

    case REQUIRED = 'REQUIRED';
}


