<?php

/**
 * ReturnShippingCostPayerEnum
 *
 * PHP version 8.1
 *
 * @package  eBay\Sell\Metadata
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Metadata API
 *
 * The Metadata API provides crucial configuration details necessary for managing listings across various eBay marketplaces. This includes retrieving detailed eBay category listing policies, such as supported item conditions and multiple-variation structures; accessing sales tax jurisdiction information for setting up tax tables in supported countries; and obtaining hazardous material and product safety label data for regulatory compliance in listing flows. The API is essential for sellers and developers needing up-to-date, marketplace-specific policy and jurisdictional information to accurately create and manage their listings.
 *
 * The version of the OpenAPI document: v1.13.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace eBay\Sell\Metadata\Model;

/**
 * ReturnShippingCostPayerEnum Class Doc Comment
 *
 * @description An enum list that defines the values you can supply for who pays for the return shipping cost. | - **BUYER**: Indicates the buyer pays for the return shipping cost.&lt;br&gt;&lt;br&gt;Note that the seller is responsible for the return shipping cost for all SNAD-related returns. - **SELLER**: Indicates the seller pays for the return shipping cost.
 * @package  eBay\Sell\Metadata
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum ReturnShippingCostPayerEnum: string
{
    case BUYER = 'BUYER';

    case SELLER = 'SELLER';
}


