<?php

/**
 * ShippingService
 *
 * PHP version 8.1
 *
 * @package  eBay\Sell\Metadata
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Metadata API
 *
 * The Metadata API has operations that retrieve configuration details pertaining to the different eBay marketplaces. In addition to marketplace information, the API also has operations that get information that helps sellers list items on eBay.
 *
 * The version of the OpenAPI document: v1.12.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace eBay\Sell\Metadata\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use eBay\Sell\Metadata\ObjectSerializer;

/**
 * ShippingService Class Doc Comment
 *
 * @description This type provides applicable shipping service metadata.
 * @package  eBay\Sell\Metadata
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class ShippingService implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'ShippingService';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'description' => 'string',
        'international_service' => 'bool',
        'max_shipping_time' => 'int',
        'min_shipping_time' => 'int',
        'package_limits' => '\eBay\Sell\Metadata\Model\PackageLimits',
        'shipping_carrier' => 'string',
        'shipping_category' => 'string',
        'shipping_cost_types' => 'string[]',
        'shipping_service' => 'string',
        'valid_for_selling_flow' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'description' => null,
        'international_service' => null,
        'max_shipping_time' => 'int32',
        'min_shipping_time' => 'int32',
        'package_limits' => null,
        'shipping_carrier' => null,
        'shipping_category' => null,
        'shipping_cost_types' => null,
        'shipping_service' => null,
        'valid_for_selling_flow' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'description' => false,
        'international_service' => false,
        'max_shipping_time' => false,
        'min_shipping_time' => false,
        'package_limits' => false,
        'shipping_carrier' => false,
        'shipping_category' => false,
        'shipping_cost_types' => false,
        'shipping_service' => false,
        'valid_for_selling_flow' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'description' => 'description',
        'international_service' => 'internationalService',
        'max_shipping_time' => 'maxShippingTime',
        'min_shipping_time' => 'minShippingTime',
        'package_limits' => 'packageLimits',
        'shipping_carrier' => 'shippingCarrier',
        'shipping_category' => 'shippingCategory',
        'shipping_cost_types' => 'shippingCostTypes',
        'shipping_service' => 'shippingService',
        'valid_for_selling_flow' => 'validForSellingFlow'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'description' => 'setDescription',
        'international_service' => 'setInternationalService',
        'max_shipping_time' => 'setMaxShippingTime',
        'min_shipping_time' => 'setMinShippingTime',
        'package_limits' => 'setPackageLimits',
        'shipping_carrier' => 'setShippingCarrier',
        'shipping_category' => 'setShippingCategory',
        'shipping_cost_types' => 'setShippingCostTypes',
        'shipping_service' => 'setShippingService',
        'valid_for_selling_flow' => 'setValidForSellingFlow'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'description' => 'getDescription',
        'international_service' => 'getInternationalService',
        'max_shipping_time' => 'getMaxShippingTime',
        'min_shipping_time' => 'getMinShippingTime',
        'package_limits' => 'getPackageLimits',
        'shipping_carrier' => 'getShippingCarrier',
        'shipping_category' => 'getShippingCategory',
        'shipping_cost_types' => 'getShippingCostTypes',
        'shipping_service' => 'getShippingService',
        'valid_for_selling_flow' => 'getValidForSellingFlow'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('international_service', $data ?? [], null);
        $this->setIfExists('max_shipping_time', $data ?? [], null);
        $this->setIfExists('min_shipping_time', $data ?? [], null);
        $this->setIfExists('package_limits', $data ?? [], null);
        $this->setIfExists('shipping_carrier', $data ?? [], null);
        $this->setIfExists('shipping_category', $data ?? [], null);
        $this->setIfExists('shipping_cost_types', $data ?? [], null);
        $this->setIfExists('shipping_service', $data ?? [], null);
        $this->setIfExists('valid_for_selling_flow', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription(): ?string
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description This field returns the localized name of the shipping service.
     *
     * @return $this
     */
    public function setDescription(?string $description): static
    {
        if (is_null($description)) {
            throw new InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets international_service
     *
     * @return bool|null
     */
    public function getInternationalService(): ?bool
    {
        return $this->container['international_service'];
    }

    /**
     * Sets international_service
     *
     * @param bool|null $international_service A value of <code>true</code> indicates that the shipping service is international. An international shipping service option is required if an item is being shipped from one country (origin) to another (destination).
     *
     * @return $this
     */
    public function setInternationalService(?bool $international_service): static
    {
        if (is_null($international_service)) {
            throw new InvalidArgumentException('non-nullable international_service cannot be null');
        }
        $this->container['international_service'] = $international_service;

        return $this;
    }

    /**
     * Gets max_shipping_time
     *
     * @return int|null
     */
    public function getMaxShippingTime(): ?int
    {
        return $this->container['max_shipping_time'];
    }

    /**
     * Sets max_shipping_time
     *
     * @param int|null $max_shipping_time This value indicates the maximum number of business days that it takes the <b>shippingCarrier</b> to ship an item using the corresponding <b>shippingService</b>.
     *
     * @return $this
     */
    public function setMaxShippingTime(?int $max_shipping_time): static
    {
        if (is_null($max_shipping_time)) {
            throw new InvalidArgumentException('non-nullable max_shipping_time cannot be null');
        }
        $this->container['max_shipping_time'] = $max_shipping_time;

        return $this;
    }

    /**
     * Gets min_shipping_time
     *
     * @return int|null
     */
    public function getMinShippingTime(): ?int
    {
        return $this->container['min_shipping_time'];
    }

    /**
     * Sets min_shipping_time
     *
     * @param int|null $min_shipping_time This value indicates the minimum number of business days that it takes the <b>shippingCarrier</b> to ship an item using the corresponding <b>shippingService</b>.
     *
     * @return $this
     */
    public function setMinShippingTime(?int $min_shipping_time): static
    {
        if (is_null($min_shipping_time)) {
            throw new InvalidArgumentException('non-nullable min_shipping_time cannot be null');
        }
        $this->container['min_shipping_time'] = $min_shipping_time;

        return $this;
    }

    /**
     * Gets package_limits
     *
     * @return \eBay\Sell\Metadata\Model\PackageLimits|null
     */
    public function getPackageLimits(): ?\eBay\Sell\Metadata\Model\PackageLimits
    {
        return $this->container['package_limits'];
    }

    /**
     * Sets package_limits
     *
     * @param \eBay\Sell\Metadata\Model\PackageLimits|null $package_limits package_limits
     *
     * @return $this
     */
    public function setPackageLimits(?\eBay\Sell\Metadata\Model\PackageLimits $package_limits): static
    {
        if (is_null($package_limits)) {
            throw new InvalidArgumentException('non-nullable package_limits cannot be null');
        }
        $this->container['package_limits'] = $package_limits;

        return $this;
    }

    /**
     * Gets shipping_carrier
     *
     * @return string|null
     */
    public function getShippingCarrier(): ?string
    {
        return $this->container['shipping_carrier'];
    }

    /**
     * Sets shipping_carrier
     *
     * @param string|null $shipping_carrier The code for the shipping carrier returned, for example, <code>UPS</code>, <code>FedEx</code>, and <code>USPS</code>.
     *
     * @return $this
     */
    public function setShippingCarrier(?string $shipping_carrier): static
    {
        if (is_null($shipping_carrier)) {
            throw new InvalidArgumentException('non-nullable shipping_carrier cannot be null');
        }
        $this->container['shipping_carrier'] = $shipping_carrier;

        return $this;
    }

    /**
     * Gets shipping_category
     *
     * @return string|null
     */
    public function getShippingCategory(): ?string
    {
        return $this->container['shipping_category'];
    }

    /**
     * Sets shipping_category
     *
     * @param string|null $shipping_category The shipping category of the shipping service including:  <code>ECONOMY</code>, <code>STANDARD</code>, <code>EXPEDITED</code>, <code>ONE_DAY</code>, <code>PICKUP</code>, and other similar categories.
     *
     * @return $this
     */
    public function setShippingCategory(?string $shipping_category): static
    {
        if (is_null($shipping_category)) {
            throw new InvalidArgumentException('non-nullable shipping_category cannot be null');
        }
        $this->container['shipping_category'] = $shipping_category;

        return $this;
    }

    /**
     * Gets shipping_cost_types
     *
     * @return string[]|null
     */
    public function getShippingCostTypes(): ?array
    {
        return $this->container['shipping_cost_types'];
    }

    /**
     * Sets shipping_cost_types
     *
     * @param string[]|null $shipping_cost_types A list of shipping cost types that this shipping service option supports. For example, <code>FLAT_RATE</code>, <code>CALCULATED</code>, and <code>FREIGHT</code>.
     *
     * @return $this
     */
    public function setShippingCostTypes(?array $shipping_cost_types): static
    {
        if (is_null($shipping_cost_types)) {
            throw new InvalidArgumentException('non-nullable shipping_cost_types cannot be null');
        }
        $this->container['shipping_cost_types'] = $shipping_cost_types;

        return $this;
    }

    /**
     * Gets shipping_service
     *
     * @return string|null
     */
    public function getShippingService(): ?string
    {
        return $this->container['shipping_service'];
    }

    /**
     * Sets shipping_service
     *
     * @param string|null $shipping_service The name of the shipping service. The shipping service named here can only be used in listings or in business policies if <b>validForSellingFlow</b> is <code>true</code>. The value returned in this field is used in listing APIs and business policies to set the shipping service.
     *
     * @return $this
     */
    public function setShippingService(?string $shipping_service): static
    {
        if (is_null($shipping_service)) {
            throw new InvalidArgumentException('non-nullable shipping_service cannot be null');
        }
        $this->container['shipping_service'] = $shipping_service;

        return $this;
    }

    /**
     * Gets valid_for_selling_flow
     *
     * @return bool|null
     */
    public function getValidForSellingFlow(): ?bool
    {
        return $this->container['valid_for_selling_flow'];
    }

    /**
     * Sets valid_for_selling_flow
     *
     * @param bool|null $valid_for_selling_flow A value of <code>true</code> indicates that the <b>shippingService</b> can be set as an available shipping service in the listing or through the fulfillment business policy.
     *
     * @return $this
     */
    public function setValidForSellingFlow(?bool $valid_for_selling_flow): static
    {
        if (is_null($valid_for_selling_flow)) {
            throw new InvalidArgumentException('non-nullable valid_for_selling_flow cannot be null');
        }
        $this->container['valid_for_selling_flow'] = $valid_for_selling_flow;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


