<?php

/**
 * SpecificationRequest
 *
 * PHP version 8.1
 *
 * @package  eBay\Sell\Metadata
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Metadata API
 *
 * The Metadata API has operations that retrieve configuration details pertaining to the different eBay marketplaces. In addition to marketplace information, the API also has operations that get information that helps sellers list items on eBay.
 *
 * The version of the OpenAPI document: v1.12.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace eBay\Sell\Metadata\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use eBay\Sell\Metadata\ObjectSerializer;

/**
 * SpecificationRequest Class Doc Comment
 *
 * @description This type provides the properties and specifications to use to search for compatibilities.
 * @package  eBay\Sell\Metadata
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class SpecificationRequest implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'SpecificationRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'category_id' => 'string',
        'compatibility_property_filters' => '\eBay\Sell\Metadata\Model\PropertyFilterInner[]',
        'dataset' => 'string',
        'dataset_property_name' => 'string[]',
        'exact_match' => 'bool',
        'pagination_input' => '\eBay\Sell\Metadata\Model\PaginationInput',
        'sort_orders' => '\eBay\Sell\Metadata\Model\SortOrderInner[]',
        'specifications' => '\eBay\Sell\Metadata\Model\PropertyFilterInner[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'category_id' => null,
        'compatibility_property_filters' => null,
        'dataset' => null,
        'dataset_property_name' => null,
        'exact_match' => null,
        'pagination_input' => null,
        'sort_orders' => null,
        'specifications' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'category_id' => false,
        'compatibility_property_filters' => false,
        'dataset' => false,
        'dataset_property_name' => false,
        'exact_match' => false,
        'pagination_input' => false,
        'sort_orders' => false,
        'specifications' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'category_id' => 'categoryId',
        'compatibility_property_filters' => 'compatibilityPropertyFilters',
        'dataset' => 'dataset',
        'dataset_property_name' => 'datasetPropertyName',
        'exact_match' => 'exactMatch',
        'pagination_input' => 'paginationInput',
        'sort_orders' => 'sortOrders',
        'specifications' => 'specifications'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'category_id' => 'setCategoryId',
        'compatibility_property_filters' => 'setCompatibilityPropertyFilters',
        'dataset' => 'setDataset',
        'dataset_property_name' => 'setDatasetPropertyName',
        'exact_match' => 'setExactMatch',
        'pagination_input' => 'setPaginationInput',
        'sort_orders' => 'setSortOrders',
        'specifications' => 'setSpecifications'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'category_id' => 'getCategoryId',
        'compatibility_property_filters' => 'getCompatibilityPropertyFilters',
        'dataset' => 'getDataset',
        'dataset_property_name' => 'getDatasetPropertyName',
        'exact_match' => 'getExactMatch',
        'pagination_input' => 'getPaginationInput',
        'sort_orders' => 'getSortOrders',
        'specifications' => 'getSpecifications'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('category_id', $data ?? [], null);
        $this->setIfExists('compatibility_property_filters', $data ?? [], null);
        $this->setIfExists('dataset', $data ?? [], null);
        $this->setIfExists('dataset_property_name', $data ?? [], null);
        $this->setIfExists('exact_match', $data ?? [], null);
        $this->setIfExists('pagination_input', $data ?? [], null);
        $this->setIfExists('sort_orders', $data ?? [], null);
        $this->setIfExists('specifications', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets category_id
     *
     * @return string|null
     */
    public function getCategoryId(): ?string
    {
        return $this->container['category_id'];
    }

    /**
     * Sets category_id
     *
     * @param string|null $category_id The unique identifier of the eBay leaf category for which compatibility details are being retrieved. This category must be a valid eBay category on the specified eBay marketplace, and the category must support parts compatibility for cars, trucks, or motorcycles.<br><br>Use the <a href=\"/api-docs/sell/metadata/resources/marketplace/methods/getAutomotivePartsCompatibilityPolicies\" target=\"_blank \">getAutomotivePartsCompatibilityPolicies</a> method to retrieve a list of categories that support parts compatibility by specification. For the categories in the response that support compatibility by specification, you’ll see <code>SPECIFICATIONS</code> as the value for the <b>compatibilityBasedOn</b> field
     *
     * @return $this
     */
    public function setCategoryId(?string $category_id): static
    {
        if (is_null($category_id)) {
            throw new InvalidArgumentException('non-nullable category_id cannot be null');
        }
        $this->container['category_id'] = $category_id;

        return $this;
    }

    /**
     * Gets compatibility_property_filters
     *
     * @return \eBay\Sell\Metadata\Model\PropertyFilterInner[]|null
     */
    public function getCompatibilityPropertyFilters(): ?array
    {
        return $this->container['compatibility_property_filters'];
    }

    /**
     * Sets compatibility_property_filters
     *
     * @param \eBay\Sell\Metadata\Model\PropertyFilterInner[]|null $compatibility_property_filters This comma-delimited array can be used to restrict the number of compatible application name-value pairs returned in the response by specifying the properties that the seller wishes to be included in the response.<br><br>Only compatible applications with the specified properties will be returned. Properties that can be specified here include make, model, year, and trim.
     *
     * @return $this
     */
    public function setCompatibilityPropertyFilters(?array $compatibility_property_filters): static
    {
        if (is_null($compatibility_property_filters)) {
            throw new InvalidArgumentException('non-nullable compatibility_property_filters cannot be null');
        }
        $this->container['compatibility_property_filters'] = $compatibility_property_filters;

        return $this;
    }

    /**
     * Gets dataset
     *
     * @return string|null
     */
    public function getDataset(): ?string
    {
        return $this->container['dataset'];
    }

    /**
     * Sets dataset
     *
     * @param string|null $dataset This field can be used to define the type of properties that will be returned in the response.<br><br> For example, if you specify <code>Searchable</code>, the compatibility details will contain properties that can be used to search for products, such as make or model.<br><br><span class=\"tablenote\"><b>Note:</b> This field cannot be used alongside <b>dataPropertyName</b>. If both are used, an error will occur.</span><br><b>Valid values:</b><ul><li><code>DisplayableProductDetails</code>: Properties for use in a user interface to describe products.</li><li><code>DisplayableSearchResults</code>: Properties for use in results for product searches.</li><li><code>Searchable</code>: Properties for use in searches.</li><li><code>Sortable</code>: Properties that are suitable for sorting.</li></ul><b>Default value:</b> <code>DisplayableSearchResults</code>
     *
     * @return $this
     */
    public function setDataset(?string $dataset): static
    {
        if (is_null($dataset)) {
            throw new InvalidArgumentException('non-nullable dataset cannot be null');
        }
        $this->container['dataset'] = $dataset;

        return $this;
    }

    /**
     * Gets dataset_property_name
     *
     * @return string[]|null
     */
    public function getDatasetPropertyName(): ?array
    {
        return $this->container['dataset_property_name'];
    }

    /**
     * Sets dataset_property_name
     *
     * @param string[]|null $dataset_property_name This comma-delimited array can be used to define the specific property name(s) that will be returned in the response.<br><br>For example, if you specify <code>Engine</code>, the result set will only contain engines that are compatible with the input criteria.<br><br><span class=\"tablenote\"><b>Note:</b> This array cannot be used alongside <b>dataset</b>. If both are used, an error will occur.</span>
     *
     * @return $this
     */
    public function setDatasetPropertyName(?array $dataset_property_name): static
    {
        if (is_null($dataset_property_name)) {
            throw new InvalidArgumentException('non-nullable dataset_property_name cannot be null');
        }
        $this->container['dataset_property_name'] = $dataset_property_name;

        return $this;
    }

    /**
     * Gets exact_match
     *
     * @return bool|null
     */
    public function getExactMatch(): ?bool
    {
        return $this->container['exact_match'];
    }

    /**
     * Sets exact_match
     *
     * @param bool|null $exact_match This boolean can be used to specify that the compatibilities returned in the response are to be defined by an exact match on the input value of specification properties.<br><br>By default, an expanded compatibility match is done when it applies, such as for Load Index, where a compatible vehicle is one that has a load index requirement that is less than or equal to the input. By specifying this field as <code>true</code>, only exact matches are returned.
     *
     * @return $this
     */
    public function setExactMatch(?bool $exact_match): static
    {
        if (is_null($exact_match)) {
            throw new InvalidArgumentException('non-nullable exact_match cannot be null');
        }
        $this->container['exact_match'] = $exact_match;

        return $this;
    }

    /**
     * Gets pagination_input
     *
     * @return \eBay\Sell\Metadata\Model\PaginationInput|null
     */
    public function getPaginationInput(): ?\eBay\Sell\Metadata\Model\PaginationInput
    {
        return $this->container['pagination_input'];
    }

    /**
     * Sets pagination_input
     *
     * @param \eBay\Sell\Metadata\Model\PaginationInput|null $pagination_input pagination_input
     *
     * @return $this
     */
    public function setPaginationInput(?\eBay\Sell\Metadata\Model\PaginationInput $pagination_input): static
    {
        if (is_null($pagination_input)) {
            throw new InvalidArgumentException('non-nullable pagination_input cannot be null');
        }
        $this->container['pagination_input'] = $pagination_input;

        return $this;
    }

    /**
     * Gets sort_orders
     *
     * @return \eBay\Sell\Metadata\Model\SortOrderInner[]|null
     */
    public function getSortOrders(): ?array
    {
        return $this->container['sort_orders'];
    }

    /**
     * Sets sort_orders
     *
     * @param \eBay\Sell\Metadata\Model\SortOrderInner[]|null $sort_orders This array specifies the sorting order of the compatibility properties. Any of the searchable properties can be used to specify search order. Up to 5 levels of sort order may be specified.<br><br><span class=\"tablenote\"><b>Note:</b> If no sort order is specified through this field, the default sort order of <b>popularity descending</b> is applied.</span>
     *
     * @return $this
     */
    public function setSortOrders(?array $sort_orders): static
    {
        if (is_null($sort_orders)) {
            throw new InvalidArgumentException('non-nullable sort_orders cannot be null');
        }
        $this->container['sort_orders'] = $sort_orders;

        return $this;
    }

    /**
     * Gets specifications
     *
     * @return \eBay\Sell\Metadata\Model\PropertyFilterInner[]|null
     */
    public function getSpecifications(): ?array
    {
        return $this->container['specifications'];
    }

    /**
     * Sets specifications
     *
     * @param \eBay\Sell\Metadata\Model\PropertyFilterInner[]|null $specifications This array defines the specifications of the part, in the form of name-value pairs, for which compatible applications will be retrieved.
     *
     * @return $this
     */
    public function setSpecifications(?array $specifications): static
    {
        if (is_null($specifications)) {
            throw new InvalidArgumentException('non-nullable specifications cannot be null');
        }
        $this->container['specifications'] = $specifications;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


