<?php
/**
 * ListingTypeEnumTest
 *
 * PHP version 8.1
 *
 * @package  eBay\Sell\Metadata
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Metadata API
 *
 * The Metadata API provides crucial configuration details necessary for managing listings across various eBay marketplaces. This includes retrieving detailed eBay category listing policies, such as supported item conditions and multiple-variation structures; accessing sales tax jurisdiction information for setting up tax tables in supported countries; and obtaining hazardous material and product safety label data for regulatory compliance in listing flows. The API is essential for sellers and developers needing up-to-date, marketplace-specific policy and jurisdictional information to accurately create and manage their listings.
 *
 * The version of the OpenAPI document: v1.13.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace eBay\Sell\Metadata\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ListingTypeEnumTest Class Doc Comment
 *
 * @description This enumerated type contains the selling formats for eBay listings. | - **AUCTION**: This value indicates that the corresponding leaf category supports auction listings. - **AD_TYPE**: This value indicates that the corresponding leaf category supports classified ads in a Real Estate category listings. - **PERSONAL_OFFER**: This value indicates that the corresponding leaf category supports Second chance offer made to a non-winning bidder listings. - **FIXED_PRICE_ITEM**: This value indicates that the corresponding leaf category supports fixed-price listings. - **LEAD_GENERATION**: This value indicates that the corresponding leaf category supports non-Real Estate classified ad listings (the &lt;code&gt;AD_TYPE&lt;/code&gt; enumeration value represents Real Estate classified ads).
 * @package     eBay\Sell\Metadata
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ListingTypeEnumTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ListingTypeEnum"
     */
    public function testListingTypeEnum()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
